regions:
- us-east-1
- us-east-2
- us-west-1
- us-west-2
- ap-northeast-1
- ap-northeast-2
- ap-northeast-3
- ap-southeast-1
- ap-southeast-2
- global

account-blacklist:
- "999999999999"

resource-types:
  excludes:
  - IAMUser
  - IAMUserPolicyAttachment
  - IAMUserAccessKey
  - Route53HostedZone
  - OSPackage
  - IAMVirtualMFADevice

accounts:
 <ACCOUNT_ID>:
     filters:
      IAMUser:
      - "aws-nuke-user"
      IAMUserPolicyAttachment:
      - property: RoleName
        value: "aws-nuke-user"
      IAMUserAccessKey:
      - property: UserName