regions:
- global

account-blacklist:
- "999999999999"

resource-types:
  excludes:
  - IAMUser
  - IAMUserPolicyAttachment
  - IAMUserAccessKey
  - IAMVirtualMFADevice
  - OSPackage

accounts:
 <ACCOUNT_ID>: